#!/bin/sh
# Embeds the skill acpx bundles in the acpx CLI, for `--skill` (#249): skills/acpx/SKILL.md from
# the acpx release below, byte for byte, lands in Sources/acpx/BundledSkill.swift with acpx's
# license, so the CLI needs no files beside it.
#
# Run it again to move to another acpx release, then pin that release's digest in
# SkillflagTests: `acpx --skill list --json` of the release installed from npm.
#
# Needs an acpx git checkout (ACPX_SRC).
set -eu

ACPX_TAG="${ACPX_TAG:-v0.19.3}"
ACPX_SRC="${ACPX_SRC:?set ACPX_SRC to an acpx git checkout}"
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
OUT="$ROOT/Sources/acpx/BundledSkill.swift"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
git -C "$ACPX_SRC" show "$ACPX_TAG:skills/acpx/SKILL.md" > "$WORK/SKILL.md"
git -C "$ACPX_SRC" show "$ACPX_TAG:LICENSE" > "$WORK/LICENSE"
if grep -q '"""######' "$WORK/SKILL.md"; then
    echo "SKILL.md holds the raw string's delimiter" >&2
    exit 1
fi

{
    printf '// Generated by scripts/skill/embed.sh — do not edit.\n'
    printf '//\n'
    printf "// skills/acpx/SKILL.md is acpx %s's, under acpx's license:\n" "$ACPX_TAG"
    printf '//\n'
    sed -e 's|^|// |' -e 's| *$||' "$WORK/LICENSE"
    printf '\n'
    printf '/// The skill acpx bundles (`skills/acpx/SKILL.md`), which `--skill` lists, shows, exports\n'
    printf '/// and installs (``Skillflag``).\n'
    printf 'enum BundledSkill {\n'
    printf '    /// The acpx release the skill is from.\n'
    printf '    static let acpxRelease = "%s"\n\n' "$ACPX_TAG"
    printf '    /// The skill'"'"'s id: the name of its directory in acpx'"'"'s `skills/`.\n'
    printf '    static let id = "acpx"\n\n'
    printf '    /// `SKILL.md`, byte for byte.\n'
    printf '    static let markdown = ######"""\n'
    cat "$WORK/SKILL.md"
    # The line break before the closing delimiter is not the string's: SKILL.md's own last one is.
    printf '\n"""######\n'
    printf '}\n'
} > "$OUT"
