#!/bin/sh
# Builds SwiftACP's flow host scripts and embeds them in the acpx CLI:
#
# - flow-runtime.mjs, the module a flow imports as "acpx/flows": acpx's own authoring
#   helpers (definition, decision, json, schema, authoring, graph) from the acpx release
#   below, bundled with the zod they validate with;
# - flow-host.mjs, the host itself, written for SwiftACP.
#
# Both land in Sources/ACPXFlows/FlowHostScripts.swift, so the CLI needs no files beside
# it. Run it again after changing flow-host.mjs, or to move to another acpx release.
#
# Needs an acpx git checkout (ACPX_SRC) and an installed acpx package (ACPX_PACKAGE), whose
# node_modules provide esbuild and zod.
set -eu

ACPX_TAG="${ACPX_TAG:-v0.19.3}"
ACPX_SRC="${ACPX_SRC:?set ACPX_SRC to an acpx git checkout}"
ACPX_PACKAGE="${ACPX_PACKAGE:?set ACPX_PACKAGE to an installed acpx package directory}"
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
ESBUILD="$ACPX_PACKAGE/node_modules/esbuild/bin/esbuild"
OUT="$ROOT/Sources/ACPXFlows/FlowHostScripts.swift"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git -C "$ACPX_SRC" archive "$ACPX_TAG" src/flows src/types.ts | tar -x -C "$WORK"
cp "$HERE/runtime-entry.ts" "$WORK/runtime-entry.ts"
ZOD_VERSION="$(sed -n 's/^  "version": "\(.*\)",$/\1/p' "$ACPX_PACKAGE/node_modules/zod/package.json")"

NODE_PATH="$ACPX_PACKAGE/node_modules" "$ESBUILD" "$WORK/runtime-entry.ts" \
    --bundle --format=esm --platform=node --target=node22 --minify --legal-comments=none \
    --outfile="$WORK/flow-runtime.mjs" --log-level=warning

embed() {
    # A raw string literal with a delimiter the script cannot contain.
    printf '    static let %s = ######"""\n' "$1"
    cat "$2"
    printf '\n"""######\n'
}

{
    printf '// Generated by scripts/flow-host/build.sh — do not edit.\n'
    printf '//\n'
    printf '// flow-runtime.mjs: acpx %s authoring helpers (MIT, (c) OpenClaw Team) with\n' "$ACPX_TAG"
    printf '// zod %s (MIT, (c) Colin McDonnell). flow-host.mjs: SwiftACP.\n' "$ZOD_VERSION"
    printf 'enum FlowHostScripts {\n'
    printf '    /// The acpx release the runtime was built from.\n'
    printf '    static let acpxRelease = "%s"\n\n' "$ACPX_TAG"
    embed runtime "$WORK/flow-runtime.mjs"
    printf '\n'
    embed host "$HERE/flow-host.mjs"
    printf '}\n'
} > "$OUT"

echo "wrote $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
